version: "3"

services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: gatsby
    volumes:
      - .:/app

  develop:
    build:
      context: .
      dockerfile: Dockerfile
    command: ${NODE_CMD}
    ports:
      - ${NODE_EXTERNAL_PORT}:${NODE_INTERNAL_PORT}
    volumes:
      - .:/app