version: "3"

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    command: ${NODE_CMD}
    ports:
      - ${NODE_EXTERNAL_PORT}:${NODE_INTERNAL_PORT}
